export const state = {
  ws: null,
  profile: { role: 'student', userId: null, email: '', firstName: '', lastName: '', className: '', courses: [] },
  authMode: 'login', // login | register | verify | reset-request | reset-confirm
  pendingEmail: '',
  classCatalog: [],
  courseCatalog: [],
  selectedCourses: [],
  rooms: [],
  currentRoom: null,
  myLog: [],
  myStats: { session: { signals: 0, calls: 0 }, total: { signals: 0, calls: 0 }, daily: {} },
  subjectStats: [],
  selectedSubject: '',
  lastAuth: null,
  poll: null,
  pollSelection: [],
  timer: null,
  assignment: null,
  grade: null,
  group: null,
  thoughtActive: false,
  pollCollapsed: false,
  homeworkItems: [],
  questionnaire: { open: false, subject: '', teacherId: '', slot: 'default', data: null, answers: {}, loading: false },
  activeQuestionnaire: null,
  feedbackInbox: [],
};