const layout = document.querySelector('.layout');

const homeworkPanel = document.createElement('div');
homeworkPanel.className = 'panel';
homeworkPanel.id = 'homeworkPanel';
homeworkPanel.innerHTML = '<h2>Hausaufgaben</h2><div id="homeworkList"><div class="small">Keine Hausaufgaben</div></div><div class="row" style="margin-top:8px;"><input id="homeworkText" style="flex:1" placeholder="Hausaufgabe fÃ¼r diesen Raum"><button id="sendHomework" class="primary">Senden</button></div>';
if (layout) layout.appendChild(homeworkPanel);

export const els = {
  layout,
  dot: document.getElementById('dot'),
  connText: document.getElementById('connText'),
  emailInput: document.getElementById('email'),
  salutationInput: document.getElementById('salutation'),
  lastNameInput: document.getElementById('lastName'),
  passwordInput: document.getElementById('password'),
  passwordConfirmInput: document.getElementById('passwordConfirm'),
  verifyCodeInput: document.getElementById('verifyCode'),
  codeLabel: document.getElementById('codeLabel'),
  saveProfileBtn: document.getElementById('saveProfile'),
  logoutBtn: document.getElementById('logoutBtn'),
  forgotBtn: document.getElementById('forgotBtn'),
  profileInfo: document.getElementById('profileInfo'),
  modeRegisterBtn: document.getElementById('modeRegister'),
  modeLoginBtn: document.getElementById('modeLogin'),
  authStatus: document.getElementById('authStatus'),
  emailRow: document.getElementById('emailRow'),
  salutationRow: document.getElementById('salutationRow'),
  lastNameRow: document.getElementById('lastNameRow'),
  passwordRow: document.getElementById('passwordRow'),
  confirmRow: document.getElementById('confirmRow'),
  codeRow: document.getElementById('codeRow'),
  profilePanel: document.getElementById('profilePanel'),
  roomsPanel: document.getElementById('roomsPanel'),
  currentRoomPanel: document.getElementById('currentRoomPanel'),
  logPanel: document.getElementById('logPanel'),
  questionsPanel: document.getElementById('questionsPanel'),
  statsPanel: document.getElementById('statsPanel'),
  toolsPanel: document.getElementById('toolsPanel'),
  classStatsPanel: document.getElementById('classStatsPanel'),
  codesPanel: document.getElementById('codesPanel'),
  adminPanel: document.getElementById('adminPanel'),
  codeClassSelect: document.getElementById('codeClassSelect'),
  fetchClassCodeBtn: document.getElementById('fetchClassCode'),
  rotateClassCodeBtn: document.getElementById('rotateClassCode'),
  classCodeInfo: document.getElementById('classCodeInfo'),
  fetchTeacherCodeBtn: document.getElementById('fetchTeacherCode'),
  rotateTeacherCodeBtn: document.getElementById('rotateTeacherCode'),
  teacherCodeInfo: document.getElementById('teacherCodeInfo'),
  pendingTeachers: document.getElementById('pendingTeachers'),
  moveStudentSelect: document.getElementById('moveStudentSelect'),
  moveClassSelect: document.getElementById('moveClassSelect'),
  moveStudentBtn: document.getElementById('moveStudentBtn'),
  moveStudentInfo: document.getElementById('moveStudentInfo'),
  banEmailInput: document.getElementById('banEmailInput'),
  banIpInput: document.getElementById('banIpInput'),
  banAddEmailBtn: document.getElementById('banAddEmail'),
  banAddIpBtn: document.getElementById('banAddIp'),
  banList: document.getElementById('banList'),
  roomNameInput: document.getElementById('roomName'),
  roomClassList: document.getElementById('roomClassList'),
  roomSubjectInput: document.getElementById('roomSubject'),
  createRoomBtn: document.getElementById('createRoom'),
  roomListEl: document.getElementById('roomList'),
  currentRoomInfo: document.getElementById('currentRoomInfo'),
  closeRoomBtn: document.getElementById('closeRoom'),
  membersBoard: document.getElementById('membersBoard'),
  logBox: document.getElementById('logBox'),
  statsGrid: document.getElementById('statsGrid'),
  questionsBox: document.getElementById('questionsBox'),
  questionBanner: document.getElementById('questionBanner'),
  questionBannerText: document.getElementById('questionBannerText'),
  questionClose: document.getElementById('questionClose'),
  catalogPanel: document.getElementById('catalogPanel'),
  newClassInput: document.getElementById('newClass'),
  newSubjectInput: document.getElementById('newSubject'),
  addClassBtn: document.getElementById('addClass'),
  addSubjectBtn: document.getElementById('addSubject'),
  catalogInfo: document.getElementById('catalogInfo'),
  teachingsPanel: document.getElementById('teachingsPanel'),
  teachClassList: document.getElementById('teachClassList'),
  teachSubjectSelect: document.getElementById('teachSubject'),
  addTeachingBtn: document.getElementById('addTeaching'),
  teachingsList: document.getElementById('teachingsList'),
  classStatsTitle: document.getElementById('classStatsTitle'),
  classStatsGrid: document.getElementById('classStatsGrid'),
  classStudentPanel: document.getElementById('classStudentPanel'),
  classStudentTitle: document.getElementById('classStudentTitle'),
  classStudentTable: document.getElementById('classStudentTable'),
  classStudentClose: document.getElementById('classStudentClose'),
  classStatsClose: document.getElementById('classStatsClose'),
  pollQuestionInput: document.getElementById('pollQuestion'),
  pollOptionsInput: document.getElementById('pollOptions'),
  pollMultipleInput: document.getElementById('pollMultiple'),
  pollAnonymousInput: document.getElementById('pollAnonymous'),
  createPollBtn: document.getElementById('createPoll'),
  endPollBtn: document.getElementById('endPoll'),
  pollResultsBox: document.getElementById('pollResults'),
  startThoughtsBtn: document.getElementById('startThoughts'),
  endThoughtsBtn: document.getElementById('endThoughts'),
  thoughtsCloud: document.getElementById('thoughtsCloud'),
  homeworkPanel,
  homeworkList: homeworkPanel.querySelector('#homeworkList'),
  homeworkText: homeworkPanel.querySelector('#homeworkText'),
  sendHomeworkBtn: homeworkPanel.querySelector('#sendHomework'),
};
